import localFont from 'next/font/local';
import Footer from "../componnent/Footer";
import Header from "../componnent/Header";
import "../globals.css";
const myFontOne = localFont({
  src: "../../public/Font/RAKIBY.ttf",
  variable: "--rakiby"
});

const myFontTwo = localFont({
  src: "../../public/Font/BeausiteFitWebTrial-Regular.woff2",
  variable: "--beaust"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFontOne.variable} ${myFontTwo.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
